//! Prague execution upgrade.

use crate::{
    eip_set,
    eips::{
        eip2537::Eip2537, eip2935::Eip2935, eip6110::Eip6110, eip7002::Eip7002, eip7623::Eip7623,
        eip7685::Eip7685, eip7702::Eip7702, eip7840::Eip7840,
    },
    execution::{ExecutionUpgrade, cancun::Cancun},
};

/// Prague execution upgrade.
pub struct Prague;

impl ExecutionUpgrade for Prague {
    type EipSet = eip_set!(
        Cancun + Eip2537,
        Eip2935,
        Eip6110,
        Eip7002,
        Eip7623,
        Eip7685,
        Eip7702,
        Eip7840
    );
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn instruction_support() {
        macro_rules! supports_mnemonics {
            ($($mnemonic: ident),+) => {
                $(assert!(Prague::supports_mnemonic(asm::Mnemonic::$mnemonic));)+
            };
        }

        supports_mnemonics!(
            STOP,
            ADD,
            MUL,
            SUB,
            DIV,
            SDIV,
            MOD,
            SMOD,
            ADDMOD,
            MULMOD,
            EXP,
            SIGNEXTEND,
            LT,
            GT,
            SLT,
            SGT,
            EQ,
            ISZERO,
            AND,
            OR,
            XOR,
            NOT,
            BYTE,
            SHL,
            SHR,
            SAR,
            KECCAK256,
            ADDRESS,
            BALANCE,
            ORIGIN,
            CALLER,
            CALLVALUE,
            CALLDATALOAD,
            CALLDATASIZE,
            CALLDATACOPY,
            CODESIZE,
            CODECOPY,
            GASPRICE,
            EXTCODESIZE,
            EXTCODECOPY,
            RETURNDATASIZE,
            RETURNDATACOPY,
            EXTCODEHASH,
            BLOCKHASH,
            COINBASE,
            TIMESTAMP,
            NUMBER,
            PREVRANDAO,
            GASLIMIT,
            CHAINID,
            SELFBALANCE,
            BASEFEE,
            BLOBHASH,
            BLOBBASEFEE,
            POP,
            MLOAD,
            MSTORE,
            MSTORE8,
            SLOAD,
            SSTORE,
            JUMP,
            JUMPI,
            PC,
            MSIZE,
            GAS,
            JUMPDEST,
            TLOAD,
            TSTORE,
            MCOPY,
            PUSH0,
            PUSH1,
            PUSH2,
            PUSH3,
            PUSH4,
            PUSH5,
            PUSH6,
            PUSH7,
            PUSH8,
            PUSH9,
            PUSH10,
            PUSH11,
            PUSH12,
            PUSH13,
            PUSH14,
            PUSH15,
            PUSH16,
            PUSH17,
            PUSH18,
            PUSH19,
            PUSH20,
            PUSH21,
            PUSH22,
            PUSH23,
            PUSH24,
            PUSH25,
            PUSH26,
            PUSH27,
            PUSH28,
            PUSH29,
            PUSH30,
            PUSH31,
            PUSH32,
            DUP1,
            DUP2,
            DUP3,
            DUP4,
            DUP5,
            DUP6,
            DUP7,
            DUP8,
            DUP9,
            DUP10,
            DUP11,
            DUP12,
            DUP13,
            DUP14,
            DUP15,
            DUP16,
            SWAP1,
            SWAP2,
            SWAP3,
            SWAP4,
            SWAP5,
            SWAP6,
            SWAP7,
            SWAP8,
            SWAP9,
            SWAP10,
            SWAP11,
            SWAP12,
            SWAP13,
            SWAP14,
            SWAP15,
            SWAP16,
            LOG0,
            LOG1,
            LOG2,
            LOG3,
            LOG4,
            CREATE,
            CALL,
            CALLCODE,
            RETURN,
            DELEGATECALL,
            CREATE2,
            STATICCALL,
            REVERT,
            INVALID,
            SELFDESTRUCT
        );
    }
}
